export {default as Navbar} from './Navbar'
export {default as About} from './About'
export {default as Buy} from './Buy'
export {default as Footer} from './Footer'
export {default as Banner} from './Banner'
export {default as Grid} from './Grid'